### ISSUE TITLE
Different versions of weeks

### ISSUE THREAD

**Issue by walinchus** [CareSet/COVID_Community_Profile_Report_FAQ#2]
There is a section by metro area which is neat. But then "cases/deaths" is only by "last week" which they define differently. For example, one Dec 20 report has last week as Dec. 13-19 and lab testing is only "last week" which they define as Dec. 11-17.

**Comment by ftrotter** [comment]
Sorry for missing this. 

You are correct there is a bit of weirdness in the time periods here, which is based on the lag in the underlying reporting. They are giving the latest data on each of these topics...
